Repository Techeer-3rd-COKKIRI/frontend, pull requests merged in 2022-12, with the labels that each got.

#6 스터디개설페이지 퍼블리싱
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/image/연필.png
  src/components/Quill/index.tsx
  src/components/createStudyInput/index.tsx
  src/components/nav/index.tsx
  src/page/Signup/index.tsx
  src/page/createStudy/index.tsx
Labels: UI디자인

#8 chore: Suspense & lazy 적용완료
  src/App.tsx
  src/Router.tsx
Labels: 환경설정

#24 스터디 개설페이지 msw api설계
  src/components/createStudyImage/index.tsx
  src/components/createStudyInput/index.tsx
  src/mocks/handlers.ts
  src/page/createStudy/index.tsx
  src/queryClient.ts
Labels: 기능구현

#22 프론트 도커설정 완료
  Dockerfile
  package.json
  vite.config.ts
Labels: 환경설정

#26 Design/#18
  src/Router.tsx
  src/assets/image/메인배너.png
  src/assets/image/바로가기버튼.png
  src/components/mystudy/index.tsx
  src/components/studyList/index.tsx
  src/page/main/index.tsx
Labels: UI디자인
