Repository Techeer-3rd-COKKIRI/frontend, pull requests merged in 2023-02, with the labels that each got.

#40 로그인 api연동
  src/GlobalStyle.tsx
  src/components/nav/index.tsx
  src/main.tsx
  src/page/LogIn/index.tsx
  src/page/createStudy/index.tsx
  src/queryClient.ts
  src/type/user.ts
Labels: 기능구현, UI디자인

#42 nav바 로그아웃기능 추가 및 디자인 수정
  src/api/user.ts
  src/assets/image/bye.png
  src/assets/image/clickMyprofile.svg
  src/assets/image/myprofile.svg
  src/components/nav/index.tsx
Labels: 기능구현, UI디자인

#46 개설페이지 api 연동
  src/components/nav/index.tsx
  src/page/createStudy/index.tsx
  src/queryClient.ts
Labels: 기능구현

#49 feat: 개설된 방 데이터 메인페이지에 전송
  src/Router.tsx
  src/components/studyIntroduce/index.tsx
  src/components/studyList/index.tsx
  src/page/main/index.tsx
  src/page/studyMain/index.tsx
Labels: 기능구현

#54 회원가입 ui 수정
  package-lock.json
  src/Router.tsx
  src/components/account/index.tsx
  src/page/Signup/index.tsx
Labels: UI디자인, 오류수정

#52 개설페이지 ui 수정
  src/components/createStudyImage/index.tsx
  src/components/createStudyInput/index.tsx
  src/page/createStudy/index.tsx
Labels: UI디자인, 리팩토링

#55 회원가입 api연동
  src/Router.tsx
  src/page/Signup/index.tsx
  src/type/user.ts
Labels: 기능구현

#61 design: 스터디메인페이지 주차버튼 3주차까지로 디자인 변경
  src/page/studyMain/index.tsx
Labels: UI디자인

#60 comment api연동
  src/components/comment/index.tsx
  src/components/commentManagement/index.tsx
  src/components/weekButton/index.tsx
  src/page/studyMain/index.tsx
  src/queryClient.ts
Labels: 기능구현

#63 로그인 / 회원가입페이지 퍼블리싱
  src/components/account/index.tsx
  src/page/LogIn/index.tsx
  src/page/Signup/index.tsx
Labels: UI디자인

#65 스터디 메인페이지 comment ui수정
  src/components/comment/index.tsx
  src/components/commentManagement/index.tsx
  src/components/weekButton/index.tsx
  src/page/studyMain/index.tsx
Labels: UI디자인, 리팩토링

#68 회원가입 페이지 유효성검사 추가
  src/components/account/index.tsx
  src/components/loginAlert/index.tsx
  src/page/LogIn/index.tsx
  src/page/Signup/index.tsx
  src/queryClient.ts
Labels: 기능구현

#72 design: 마이페이지 준비중ui완료
  src/Router.tsx
  src/assets/image/preparing.png
  src/page/profile/index.tsx
Labels: UI디자인

#75 내 스터디 로그인되어 있을때만 보여주기
  src/components/commentManagement/index.tsx
  src/components/nonStudy/index.tsx
  src/components/studyList/index.tsx
  src/page/LogIn/index.tsx
  src/page/createStudy/index.tsx
  src/page/main/index.tsx
Labels: 기능구현, UI디자인

#77 스터디 메인페이지 ui 수정
  src/components/nonStudy/index.tsx
  src/components/recruitingBox/index.tsx
  src/components/studyIntroduce/index.tsx
  src/page/profile/index.tsx
  src/page/studyMain/index.tsx
Labels: UI디자인, 리팩토링

#79 모든 페이지 react-query 커스텀 훅으로 재정의
  src/App.tsx
  src/components/account/index.tsx
  src/components/createStudyImage/index.tsx
  src/components/nav/index.tsx
  src/hook/createStudy/usePOSTRegistration.ts
  src/hook/login/usePOSTLogin.ts
  src/hook/main/useGETMyStudyList.ts
  src/hook/main/useGETStudyList.ts
  src/hook/nav/useGETLogout.ts
  src/hook/signup/useGETDuplication.ts
  src/hook/signup/usePOSTSignUp.ts
  src/page/LogIn/index.tsx
  src/page/Signup/index.tsx
  src/page/createStudy/index.tsx
  src/page/main/index.tsx
  src/page/studyMain/index.tsx
  src/queryClient.ts
  src/type/user.ts
Labels: 리팩토링

#81 refactor: nav바 웹 접근성 속성 추가
  src/components/nav/index.tsx
Labels: 리팩토링

#83 refactor : 로그인 & 회원가입 페이지 웹 접근성 속성추가
  src/page/LogIn/index.tsx
  src/page/Signup/index.tsx
Labels: 리팩토링

#85 refactor : 스터디메인페이지 & 메인페이지 리팩토링
  src/components/commentManagement/index.tsx
  src/components/studyIntroduce/index.tsx
  src/components/studyList/index.tsx
  src/components/userStudy/index.tsx
  src/hook/createStudy/useGETComment.ts
  src/hook/createStudy/usePOSTComment.ts
  src/page/main/index.tsx
  src/page/studyMain/index.tsx
Labels: 리팩토링

#88 메인페이지 페이지네이션 캐시 적용
  package-lock.json
  package.json
  src/components/studyList/index.tsx
  src/hook/main/useGETStudyList.ts
  src/hook/nav/useGETLogout.ts
  src/main.tsx
  src/page/main/index.tsx
Labels: 기능구현
